import os
import sys
from google.adk.agents import Agent
from google.adk.tools.mcp_tool import McpToolset, StdioConnectionParams
from mcp import StdioServerParameters
from google.adk.runners import InMemoryRunner

def main():
    terraform_connection = StdioConnectionParams(
        server_params=StdioServerParameters(
            command="npx",
            args=["-y", "hashicorp/terraform-mcp-server"]
        )
    )

    try:
        terraform_tools = McpToolset(connection_params=terraform_connection)
    except Exception as e:
        print(f"Failed to initialize MCP toolset: {e}")
        sys.exit(1)

    reviewer_agent = Agent(
        name="GCP_PR_Reviewer",
        model="gemini-2.5-pro",
        instruction="""
        You are an expert Google Cloud Platform (GCP) Security Architect. 
        Your job is to review proposed Terraform code via a git diff. 
        You MUST use your MCP tools to check the official 'hashicorp/google' 
        provider schemas to ensure the code is valid, has no syntax typos, and uses up-to-date syntax.
        Focus your review on security best practices and highlighting syntax errors.
        Output your review in clean Markdown format.
        """,
        tools=[terraform_tools]
    )

    # Read the diff file generated by GitHub Actions
    diff_content = "No diff provided."
    if os.path.exists("pr_diff.txt"):
        with open("pr_diff.txt", "r") as f:
            diff_content = f.read()
    
    print("Agent is analyzing the git diff and querying the Terraform Registry...")
    
    runner = InMemoryRunner(agent=reviewer_agent)
    
    prompt = f"Please review this Terraform git diff for GCP security and syntax issues:\n\n{diff_content}"
    
    events = runner.run(
        user_id="github_actions", 
        session_id="pr_review_session", 
        new_message=prompt
    )
    
    for event in events:
        if hasattr(event, 'is_final_response') and event.is_final_response():
             if hasattr(event, 'content') and event.content and event.content.parts:
                 print(event.content.parts[0].text)
        elif hasattr(event, 'text') and event.text:
             print(event.text, end="", flush=True)

if __name__ == "__main__":
    main()
